Use Swift Struct instead of String as the key in the cache.
IBAnimatable/IBAnimatable pull request #373
Opened 2016-12-07 21:30 UTC by mmadjer

2016-12-07 23:39 UTC, JakeLin requested changes
Can you check whether we can use the enums `PresentationAnimationType` and `TransitionAnimationType` as the key?

2016-12-07 23:39 UTC, JakeLin commented on IBAnimatable/PresentationPresenterChacheKey.swift
> +struct PresentationPresenterChacheKey: Hashable {
Can we directly use `PresentationAnimationType` enum as the key, and let `PresentationAnimationType: Hashable`  and provide ` static func == (lhs: PresentationPresenterChacheKey, rhs: PresentationPresenterChacheKey)`? If we can, then we don't need the additional struct. enum is also a value type.

2016-12-07 23:42 UTC, JakeLin commented
@mmadjer thanks for your PR. Sorry, I have to disappoint you because I think we may be able to use the enums as the key. Can you double check this approach for me?  We also need to rebase since there is some conflict in `TransitionPresenterManager.swift`.

2016-12-07 23:55 UTC, mmadjer commented on IBAnimatable/PresentationPresenterChacheKey.swift
> +struct PresentationPresenterChacheKey: Hashable {
I thought about that but could not find a proper way so far. I will have another look.

2016-12-08 00:09 UTC, mmadjer commented
Ok, I applied the Hashable to the two enums and using it as the key

2016-12-08 00:44 UTC, JakeLin approved these changes
Perfect, looks better.

2016-12-08 00:44 UTC, JakeLin commented on IBAnimatable/PresentationAnimationType.swift
> +extension PresentationAnimationType: Hashable {
Perfect 👍

2016-12-08 00:46 UTC, JakeLin commented
@mmadjer Thanks for the super quick update, LGTM, can you do a rebase from the master and merge it when you free it is ready.

2016-12-08 15:46 UTC, JakeLin approved these changes
perfect, I always forget about it.

2016-12-08 15:53 UTC, tbaranes commented on CHANGELOG.md
> +- Use Swift Enum as key in our internal presentation and transition cache.
Not sure that we should write a line about this since it's an internal change

2016-12-08 15:54 UTC, tbaranes approved these changes

2016-12-08 15:54 UTC, tbaranes commented
Not sure that we should add an entry in the CHANGELOG since it's an internal change. What do you think?

2016-12-08 16:14 UTC, JakeLin commented
@tbaranes, IMO we need that. It maybe a breaking change for someone uses the Singleton directly (not 💯 % sure since I am replying this on my mobile and didn't check the source code). That record can help the user find the issue.

2016-12-10 08:08 UTC, merged