Add `AnimatableTableViewController` with designable `UIRefreshControl`
IBAnimatable/IBAnimatable pull request #425
Opened 2017-03-31 07:12 UTC by phimage

and other features same as `AnimatableViewController`

`RefreshControlDesignable` allow to custom the internal `UIRefreshControl`

`UIRefreshControl` must not be set in subview but using refreshControl attribute of `UITableViewController`

ReStart of PR #418 due to many conflict
Modification since review by @tbaranes and @JakeLin 
- remove some space and add missing open on IBoutlet variable copied from AnimatableViewController
- add `TimeLineTableViewController` in demo app , to show how refresh control could be customised (simulate the refresh using `DispatchQueue`)
- fix a bug : if view not already loaded. If view not loaded, refreshControl could not be set

2017-03-31 07:21 UTC, tbaranes requested changes
I let you a few more minor comments, if you can take a look at them... :)

Also, a new swiftlint warning appeared since we enabled `line_length`, can you take care of it? If you want to see the warnings directly in Xcode, you just have to install [SwiftLint](https://github.com/realm/SwiftLint)

2017-03-31 07:21 UTC, tbaranes commented on CHANGELOG.md
> +CHANGELOG
There's a `CHANGELOG` to remove here!

2017-03-31 07:21 UTC, tbaranes commented on Documentation/APIs.md
> +Display a `UIRefreshControl` in `AnimatableTableViewController`
I wouldn't add this line, I think the protocol name is clear enough (moreover, we may conform to this protocol in other classes).

2017-03-31 07:21 UTC, tbaranes commented on IBAnimatable/AnimatableTableViewController.swift
> +//  AnimatableTableViewController.swift
You can remove these two lines. Take a look at the other headers of the project, we are just keeping the author lines.

2017-03-31 07:21 UTC, tbaranes commented on IBAnimatable/RefreshControlerDesignable.swift
> +    if isViewLoaded {
Guard?

2017-03-31 07:21 UTC, tbaranes commented on IBAnimatableApp/TimeLineTableViewController.swift
> +    DispatchQueue.background.after(time) {
Why not directly running this on `main`?

2017-03-31 07:21 UTC, tbaranes commented on IBAnimatableApp/TimeLineTableViewController.swift
> +    if time < 0 {
guard?

2017-03-31 07:33 UTC, tbaranes commented
One more thing that we should have precise it earlier, my apologies. We don't add features to the `Demo.storyboard`, but directly in the `Playground` app which is more a showoff of all the features available in `IBAnimatable`.

For the refresh control, you could add an entry in: `Playground` -> `User Interface` -> `Refresh Control`.

Sorry for not letting you know about this before 😟

2017-03-31 07:35 UTC, phimage commented on IBAnimatableApp/TimeLineTableViewController.swift
> +    DispatchQueue.background.after(time) {
To simulate a good practice, doing a  job in background like get data from network

2017-03-31 07:35 UTC, phimage commented
I use swiftlint and update it
I do some warning fix, maybe I override it, I will take care of it

2017-03-31 07:37 UTC, phimage commented on IBAnimatable/RefreshControlerDesignable.swift
> +    if isViewLoaded {
agree

2017-03-31 07:38 UTC, phimage commented on IBAnimatableApp/TimeLineTableViewController.swift
> +    if time < 0 {
ummm here not agree `if` is shorter and more understandable  but I will do it

2017-03-31 07:48 UTC, phimage commented
I have no time to make new storyboards in playground 
And I have no internet at home currently, could merge without the demo?

2017-03-31 07:51 UTC, tbaranes approved these changes
Let's wait for @JakeLin review, but  I'm ok to merge it without the demo. We can add it later! Thanks for taking care of the comments.

2017-04-01 12:37 UTC, JakeLin approved these changes
👍 Well done @phimage

2017-04-01 12:37 UTC, JakeLin commented on IBAnimatable/AnimatableTableViewController.swift
> +  @IBInspectable open var _transitionAnimationType: String? {
I think we don't want that to be `open` and let it only visible in Interface Builder. We can remove `open` and let it as  the default `internal`.

2017-04-01 12:37 UTC, JakeLin commented on IBAnimatable/AnimatableTableViewController.swift
> +  @IBInspectable open var _interactiveGestureType: String? {
Same comment as above.

2017-04-01 12:37 UTC, JakeLin commented on IBAnimatableApp/RefreshTableViewController.swift
> +public class RefreshTableViewController: AnimatableTableViewController {
Nice demo app 👍

2017-04-01 12:40 UTC, merged

2017-04-01 12:53 UTC, JakeLin commented
@phimage I have fixed my comment and merged the PR now 🎉🎉🎉. Thank you very much for creating such a great feature for IBAnimatable. It makes our life easier to configure the refersh control in Interface Builder.

For `@IBInspectable var _transitionAnimationType: String?`, because Interface Builder can't support enum. And we want to have nice programmatical API with strongly type like `open var transitionAnimationType: TransitionAnimationType = .none`. To do that, we found out a workaround, we use `String` as the type to make the inspectable property can be configured in Interface Builder. But don't want the user/client code to see `_transitionAnimationType`, then we make them as `internal`. In that case, we can configure `transitionAnimationType` in Interface Builder and use it in code as an enum. More info can be found in #218 @lastMove and @tbaranes did a great job on that.

2017-04-01 14:29 UTC, tbaranes commented
For your information, I added an entry in #238 in order to not forget that we have to update the playground storyboard in order to have a demo for refresh control.