Add AnimatableTabBarController to support custom transition animation
IBAnimatable/IBAnimatable pull request #443
Opened 2017-04-11 18:48 UTC by phimage

Same as `AnimatableNavigationController` with reverse animation when we can using child controller index

Added to the demo too, near the other tab bar controller where the animation is coded, not configured using storyboard

2017-04-12 07:21 UTC, tbaranes requested changes
Looks good, I just let you a small a few code style comments 👍 

Can you also update the CHANGELOG?

2017-04-12 07:21 UTC, tbaranes commented on IBAnimatable/Navigator.swift
> +    } else {
The else is not mandatory since the if returns

2017-04-12 07:21 UTC, tbaranes commented on IBAnimatable/Navigator.swift
> +      } else {
Same here, you can drop the else (if that's a copy from elsewhere in the code, you can remove it there as well)

2017-04-12 07:26 UTC, tbaranes commented
_The following comments is not directly related to this PR_

I'm wondering, should we move the both tabBar examples in the `Transition` part (by diving in 3 subnavigations) directly?

2017-04-12 07:31 UTC, phimage commented on IBAnimatable/Navigator.swift
> +      } else {
Yes it's a copy paste like always, I am a copy past coder 😉 

here I think I could do
```swift
return interactiveAnimator?.interacting
```
no if else

2017-04-12 07:32 UTC, phimage commented on IBAnimatable/Navigator.swift
> +    } else {
I can simplify the code here, and I will remove unnecessary else if there is some return

2017-04-12 07:34 UTC, tbaranes commented on IBAnimatable/Navigator.swift
> +      } else {
Even better!

2017-04-13 06:14 UTC, tbaranes approved these changes

2017-04-17 01:09 UTC, JakeLin approved these changes
Great PR. Animatable everything 💪

2017-04-17 01:11 UTC, JakeLin commented
@phimage Great PR 👍👍👍, can you merge it when you feel it is ready?

2017-04-17 10:04 UTC, merged