Support timing function for animation. Fix #12 #13
IBAnimatable/IBAnimatable pull request #478
Opened 2017-05-11 06:26 UTC by phimage

Re pull #456
Timing function enum added `TiminFunctionType`
  - Add it to `Animatable` objects and `AnimationConfiguration`
  - Use this enum when possible instead of `CAMediaTimingFunction`

TODO
- [x] add more type in enum (see `extension CAMediaTimingFunction`)
- [x] add more type in enum  see `CAMediaTimingFunction(` contructors in code
- [x] add custom type with control points in enum ?
- [x] manage spring animation or not, animation default value
- [x] Add an example
- [ ] Update CHANGELOG
- [ ] Documentation

2017-05-15 07:44 UTC, tbaranes commented
@phimage Sorry it takes me time to review it, it's quite big and a lot to digest! 
I have already a first comment: can you update the docs? I think you will the one to update is `Documentation/APIs.md`

2017-05-15 07:49 UTC, phimage commented
No problem!

API doc has not been reverted https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/APIs.md
I add `timingFunction`  in "Animatable protocol" section.
If you think I can add something elsewhere, I will do it :)

2017-05-15 08:02 UTC, tbaranes requested changes
That's a HUGE work, thanks for doing this, it's an awesome feature.
I let a few comments, mainly typos / minor stuff, it looks pretty good to me 👍 

Can you add the docs update once more? I think that's enough.

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +    case "easeinsine":
Can you add a comment as the ones above to keep the same structure as the enum?

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +
Typo: there's one newline to remove

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +    default:
Same here, I know it's already explicit, but I think it's better to keep the same structure as the enums. It helps to follow

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +    switch self {
Same as above, if you can add the comments to separate the main groups

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +@available(iOSApplicationExtension 10.0, *)
`iOSApplicationExtension`, did you mean `iOS`?

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +internal extension CAAnimation {
Is there a reason to explicitly make it `internal`?

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +  // conveniant setter, getter not implemented
Typo:  `conveniant` -> `convenient`

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatableApp/AnimationsTimingFunctionViewController.swift
> +class AnimationsTimingFunctionViewController: UIViewController {
final

2017-05-15 08:02 UTC, tbaranes commented on IBAnimatableApp/AnimationsViewController.swift
>  class AnimationsViewController: UIViewController {
final

2017-05-15 08:16 UTC, phimage commented on IBAnimatable/TimingFunctionType.swift
> +internal extension CAAnimation {
It's a way for me to mark dangerous extension
I want to use it internally but never let it public, or someone else does it.

With `internal` explicitly marked, people ask themselves why and edit carefully

2017-05-15 08:18 UTC, tbaranes commented
Just tested the example, pretty cool. A few points:

- At first, I though that the timing function will update the animation. Since it doesn't, you should either do it, or refactoring makes a subsections to "Animations" to have two possibilities: "View Animations", and "Timing functions"
- The image in the navigation bar isn't explicit enough (I didn't get it at first), if you choose option 1 from the previous point, we should replace the image by a text, or move the button in a place even more visible / explicit
- Since some `timingFunctions` are quite long, they are truncated in the picker. Can we add the selected name somewhere? Below the graph for example. I think we have this issue in others picker as well, time to take care of this by starting with this one? 😬

2017-05-15 08:18 UTC, phimage commented on IBAnimatableApp/AnimationsViewController.swift
>  class AnimationsViewController: UIViewController {
I think do a PR to set all `final` it's a better choice
Because here it's not a new code here. But I copy this code to make my new controller :-)

2017-05-15 08:22 UTC, tbaranes commented on IBAnimatableApp/AnimationsViewController.swift
>  class AnimationsViewController: UIViewController {
Yeah, I know that we didn't add the final at the beginning of this project, we should have this in our roadmap: add all the missing finals 💥

2017-05-15 08:44 UTC, phimage commented
The animation is updated in the previous view, `TimingFunctionPickDelegate` do it

But not all animation are compatible ie. Spring animation are not compatible
In the same way velocity, dumping are only for spring animation and update it will not affect a lot of animations
Maybe a documentation file with a list of animation with two columns: Spring animation and timing function animation(or cubic animation) will be necessary

I edit moveTo and moveBy to be compliant with the two modes.

---
Yes, the image is not explicit
I take an available image, a timer. I think about putting a timing function graph but failed to create it using my TimingFunctionView in navigation bar items.

2017-05-15 21:07 UTC, phimage commented
So new change added

- back button and navigation title for the timing function picker
- icon changed to a Gear, and the button is enabled only if the selected animation is configurable using the timing function

Added on AnimationType two compute boolean variable to know is the animation use velocity and damping or use timing function
This method could help for future animation documentations

2017-05-15 21:08 UTC, SD10 commented
@phimage this is great work! I may be able to leverage this approach to do more cleanup or adopt a similar strategy. love it!

2017-05-16 06:40 UTC, tbaranes commented on IBAnimatable/TimingFunctionType.swift
> +    switch self {
Github didn't see as fixed, but it's fixed!

2017-05-16 06:46 UTC, tbaranes requested changes
@phimage Awesome! I agree with you that a docs about timing function compatibility would be great, but we can merged that one first. So, just the missing entry in the docs and that's ready to go 👍

2017-05-16 06:50 UTC, phimage commented
For the doc, as I say, I do already something in main branch, see Animatable protocol
https://github.com/IBAnimatable/IBAnimatable/blob/master/Documentation/APIs.md

2017-05-16 06:59 UTC, tbaranes approved these changes
My bad, I misunderstood 😶

2017-05-17 04:34 UTC, JakeLin approved these changes
All good, great work 👍👍👍. Look forward to using it.

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/ActivityIndicatorAnimationOrbit.swift
> +    opacityAnimation.timingFunctionsType = [.linear, .easeOutExpo]
good to encapsulate to an extension for timing function.

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/Animatable.swift
> +public extension Animatable {
I hope Swift can support the syntax like `public extension Animatable where Self: UIView or UIBarItem` later.

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/Animatable.swift
> +      animatePosition(path: path, configuration: configuration, completion: completion)
Cool, before iOS 10, only Core Animation can apply custom timing.

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/Animatable.swift
> +  public var isCubic: Bool {
Should it call something like `doesSupportTimingFunction`? I am not good at naming though 😂

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/AnimatableBarButtonItem.swift
> +  @IBInspectable open var _timingFunction: String = "" {
This one should not be `open`. It only is used in Interface Builder. Please have a look at the comment around https://github.com/IBAnimatable/IBAnimatable/issues/218#issuecomment-230324948 . We don't want the `_` properties be used in programmatical APIs.

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/AnimatedTransitioning.swift
> +      transition.timingFunctionType = .easeOutCubic
Great 🎉

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/TimingFunctionType.swift
> +  // from http://easings.net/
👍

2017-05-17 04:34 UTC, JakeLin commented on IBAnimatable/TimingFunctionType.swift
> +  var cubicTimingParameters: UICubicTimingParameters {
Supper cool to support `UIPropertyAnimator` API.

2017-05-17 04:36 UTC, JakeLin commented
@phimage thanks for such a great PR. I think PR is ready to go. Please have a look at this comment https://github.com/IBAnimatable/IBAnimatable/pull/478#discussion_r116907694 for the `_timingFunction`. It should be `internal` like the other `_` properties.

2017-05-17 08:02 UTC, merged

2017-05-18 01:24 UTC, JakeLin commented
@phimage Well done 🎉🎉🎉🎉🎉🎉