Allow users to set text, edit, and placeholder rects in PaddingDesignable
IBAnimatable/IBAnimatable pull request #492
Opened 2017-06-02 06:34 UTC by SD10

### Summary of Pull Request:
This change would expose 9 new IBInspectable properties and replace the old PaddingDesignable API:

Replaces:
`paddingLeft`, `paddingRight`, `paddingSide`

Adds:
`leftTextPadding`, `rightTextPadding`, `sideTextPadding`
`leftEditPadding`, `rightEditPadding`, `sideEditPadding`
`leftPlaceholderPadding`, `rightPlaceholderPadding`, `sidePlaceholderPadding`

### Considerations:
I've thought about removing the `side` properties as to remove some bloat for this feature.

I think it's pretty simple to set both left and right if you want padding on both sides, but I added them to mimick the feature we had before.

I'm also considering renaming the designable protocol to `TextFieldPaddingDesignable` because I would like to add `TextViewPaddingDesignable` next and there's not enough in common in these implementations for a single protocol.

### To Do:
[ ] CHANGELOG
[ ] Update Documentation

2017-06-02 06:51 UTC, JakeLin requested changes
We discussed this before, your approach will have better control. I give 👍 for this PR. There are some breaking changes,can you update the CHANGELOG. let's discuss how can we ship it.

2017-06-02 06:51 UTC, JakeLin commented on IBAnimatable/IBAnimatableTests/TestProtocols/PaddingDesignableTests.swift
> +  case left(CGFloat)
I like this idea, can we use it in our real API for the library? But don't know how to support IB yet.

2017-06-02 06:54 UTC, SD10 commented on IBAnimatable/IBAnimatableTests/TestProtocols/PaddingDesignableTests.swift
> +  case left(CGFloat)
I have to see if this can be used instead of the helper methods in `PaddingDesignable`.
Less code repetition.

2017-06-02 10:06 UTC, tbaranes commented
Looks good beside the missing points your reported :)

2017-06-03 04:47 UTC, JakeLin commented
Because there are breaking changes, I came up an idea, Should we keep the old variables, for example, paddingLeft will apply to all leftTextPadding, leftEditPadding and leftPlaceholderPadding . If those will have more priority, if we set leftTextPadding and paddingLeft. We use leftTextPadding over paddingLeft. I know the names are not consistent, it should be leftPadding instead of paddingLeft. But I think we need to fix it for next big release. Can I have you guys opinions on this? @SD10 @tbaranes thanks

2017-06-03 06:14 UTC, SD10 commented
I don't think we should be too concerned about API breaking changes if they enhance they project. 
I hope I can add a lot more value to IBAnimatable in the long run so breaking changes will be inevitable.

That being said, I do think heavily documenting these changes and providing releases accordingly is extremely important.

One approach I think we could take is to do something like this:
We can use an `@available` attribute to trigger a deprecation warning on the old API
Then call the new implementation from within that API. 

For example:

```Swift
public protocol PaddingDesignable: class {

  @available(*, deprecated: 4.2.0, message: "Deprecated. Please use leftTextPadding, leftEditPadding, leftPlaceholderPadding.")
  var paddingLeft: CGFloat { get set }
  
  var leftTextPadding: CGFloat { get set }
  var leftEditPadding: CGFloat { get set }
  var leftPlaceholderPadding: CGFloat { get set }
  
}

extension PaddingDesignable {

  var paddingLeft: CGFloat {
    get {
      return max(leftTextPadding, leftEditPadding, leftPlaceholderPadding)
    }
    set {
      leftTextPadding = newValue
      leftEditPadding = newValue
      leftPlaceholderPadding = newValue
    }
  }
}
```
We could even add a warning to the message saying that in `IBAnimatable 5.0` this property will be dropped completely. It's like a way of phasing out the old API.

2017-06-03 06:32 UTC, SD10 commented
Another concern I have regarding keeping the old API is then we would have a total of 12 `@IBInspectable` properties just for the padding of a `UITextField`. I already felt unease about adding 9 with the new API and was considering removing the `side` related properties :(

2017-06-03 11:46 UTC, JakeLin commented
I have the same concern, in most of cases, we use the same padding for text, edit and placeholder. Why don't we use only three properties instead of nine? But we use your better implementation to configure three internally. If someone has the requirement to have different paddings for text, edit and placeholder. Then we add that back. If we have three different properties for one padding, the user has to put the same number in three places.  How do you think?

Thanks
Jake
Sent from my iPhone

> On 3 Jun 2017, at 4:32 pm, Steven Deutsch <notifications@github.com> wrote:
> 
> Another concern I have regarding keeping the old API is then we would have a total of 12 @IBInspectable properties just for the padding of a UITextField. I already felt unease about adding 9 with the new API and was considering removing the side related properties :(
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-06-03 17:08 UTC, SD10 commented
I agree. I can't think of a use case where I'd want to have different padding for the text rect, edit rect, and placeholder rect. It's usually the same on all 3. 

So just to make sure we're on the same page, let's stick to just 3 properties but we'll configure the bounds internally because it will be more performant than having the overhead of a UIView.

Good thinking to keep it simple.

2017-06-04 23:22 UTC, JakeLin commented
Cool, can we go ahead with only three properties first, add more if needed in the future?

2017-06-08 02:42 UTC, SD10 commented on IBAnimatable/IBAnimatableTests/TestProtocols/PaddingDesignableTests.swift
> +  case left(CGFloat)
Couldn't manage to reuse this code internally, just helps clean up testing

2017-06-08 02:50 UTC, SD10 commented
@JakeLin alright I kept the same API and updated the implementation, so no changes to Documentation. Just need to add CHANGELOG entry. Let me know what you think.

2017-06-08 06:17 UTC, tbaranes approved these changes

2017-06-09 01:28 UTC, JakeLin approved these changes
👍 expect for a comment

2017-06-09 01:28 UTC, JakeLin commented on Sources/Protocols/Designable/PaddingDesignable.swift
> +      return insets(left: paddingLeft, right: paddingRight)
How about one of this property is nan? We may need to check individually

2017-06-09 01:28 UTC, JakeLin commented on Sources/Views/AnimatableTextField.swift
>    }
👍 expect for a comment

2017-06-09 02:40 UTC, SD10 commented on Sources/Protocols/Designable/PaddingDesignable.swift
> +      return insets(left: paddingLeft, right: paddingRight)
I did the check inside of `insets(left:right:)`. If either `isNaN` it will default to 0. 
I could extract the logic if it's not clear.

2017-06-09 02:41 UTC, SD10 commented on Sources/Views/AnimatableTextField.swift
>    }
Except**? Meaning you would like me to add some comments? 😅 Sorry

2017-06-09 07:45 UTC, JakeLin commented on Sources/Views/AnimatableTextField.swift
>    }
No, I mean my comment😅 I think you are good to go.

2017-06-09 07:46 UTC, JakeLin commented on Sources/Protocols/Designable/PaddingDesignable.swift
> +      return insets(left: paddingLeft, right: paddingRight)
Good👍

2017-06-09 19:53 UTC, merged